ls:
  src:
    .js: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
    .spec.ts: kebab-case
    .png: kebab-case
    .scss: kebab-case | snake-case
    .vue: PascalCase

    locale:
      .ts: pointcase