name: Test

on:
  push:
    paths:
      - 'src/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install moudules
        run: yarn
      - name: Run tests
        run: yarn test:unit